### ISSUE TITLE
Cross-Platform testing

### ISSUE THREAD

**Issue by Manjilan** [chingu-voyages/v8-geckos-team-12#61]
Testing App on All platforms and check the features.

**Comment by helloRupa** [comment]
Includes mobile!

**Comment by helloRupa** [comment]
On mobile, the scroll behavior is strange: all of the components have their own scroll - the weather is scrollable, for example. If the modules were instead fully expanded with no scroll of their own, it would be a nicer experience.

The weather module doesn't align content properly for the 1-day forecast: the image is not centered. It is offset to the left.

In the footer, the Settings link overlaps the footer text.

**Comment by chrisczach** [comment]
I just noticed a weird bug, when you click on the 5 day forecast and then refresh the page it responds with a [page not found.](https://development--geckos.netlify.com/5days) Might be easier to use state to handle toggling between one day and five day instead of using routes.

**Comment by Manjilan** [comment]
I'll fix it when I get home. Seems like adding a # to the route is the solution.

**Comment by chrisczach** [comment]
I'm having some issues with the settings modal on mobile, can you please check on your phones to see if you guys are having issues also. Sometimes it takes a while for the modal to come up or sometimes it doesn't load at all and changing the settings sometimes happens instantly, is sometimes delayed, and sometimes unresponsive, not sure if it's weird bug on my end or if everyone else sees it.

**Comment by realbwoi** [comment]
My tests are a little laggy. I have yet to see it not work though, as each
attempt has loaded for me. I'll try more just to see. I think it has to do
with the API response time if anything.

**Comment by helloRupa** [comment]
The settings modal comes up fine for me without lag on mobile, but there is lag when I tap a setting - it takes a moment for the setting to move from active to inactive and vice versa.

**Comment by chrisczach** [comment]
Does it lock up for you when you try to toggle the theme colors several times in a row? I think that the lag might be because of saving the state to local storage, I'm not sure why but on my phone it becomes unresponsive if I toggle the theme several times. I might try changing how saving to local storage is handled to see if the issue is related.

**Comment by helloRupa** [comment]
It doesn't lock up at all for me. I'm using an Android phone running Chrome and Firefox Focus.
